name: CI RSpec Tests
on: [pull_request]
  push:
   paths:
   - 'backend/**'
  pull_request:
    paths:
    - 'backend/**'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      api-dir: ./backend

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.4

      - name: Build and test with rspec
        working-directory: ${{env.api-dir}}
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
        run: bundle exec rspec
